set(JSONCPP_WITH_TESTS OFF)
set(JSONCPP_WITH_POST_BUILD_UNITTEST OFF)
set(JSONCPP_WITH_WARNING_AS_ERROR OFF)
set(JSONCPP_WITH_STRICT_ISO ON)
set(JSONCPP_WITH_PKGCONFIG_SUPPORT ON)
set(JSONCPP_WITH_CMAKE_PACKAGE ON)
set(JSONCPP_WITH_EXAMPLE OFF)
set(JSONCPP_STATIC_WINDOWS_RUNTIME OFF)
set(BUILD_SHARED_LIBS ON)
set(BUILD_STATIC_LIBS ON)
set(BUILD_OBJECT_LIBS ON)
add_subdirectory(jsoncpp)

set(BUILD_SHARED_LIBS OFF)
set(SPDLOG_SYSTEM_INCLUDES OFF)
set(SPDLOG_INSTALL ON)
set(SPDLOG_USE_STD_FORMAT OFF)
set(SPDLOG_FMT_EXTERNAL OFF)
set(SPDLOG_FMT_EXTERNAL_HO OFF)
set(SPDLOG_NO_EXCEPTIONS OFF)
add_subdirectory(spdlog)

set(ZLIB_BUILD_EXAMPLES OFF)
add_subdirectory(zlib)

set(BUILD_TESTS OFF)
set(WITH_PERF_TOOL OFF)
set(ZMQ_BUILD_TESTS OFF)
add_subdirectory(libzmq)
